### ISSUE TITLE
Set src home path in VSC?

### ISSUE THREAD

**Issue by kristianmandrup** [Jarrio/Haxe-Manager#15]
Tried to install the Haxe Manager in VSC. Asked me for Path and said Press ENTER.
Accidentally tried just pressing ENTER with empty path. Invalid path, but now not sure how to set a valid home path for the plugin.

**Comment by kristianmandrup** [comment]
Ah, just had to uninstall, reinstall, then reboot VSC again. Cheers!

**Comment by Jarrio** [comment]
Just for future reference you're able to change the path by going to `File` -> `Preferences` -> `Settings` the property to look for/set is `"hxmanager.projectsRoot"`

**Comment by kristianmandrup** [comment]
Great. Please add this to the plugin docs. Would have liked to see this on the doc page displayed in VSC after install.
