### ISSUE TITLE
Suggestion: And __template folder to haxe directory

### ISSUE THREAD

**Issue by hoseyjoe** [Jarrio/Haxe-Manager#4]
It would be nice to have the template directory copied to the haxe project created folder.  Something like {haxeInstallation}/__templates

This would allow end users to create their own templates.  Assuming, of course,  that Haxe-Manager was able to traverse the folder and provide a drop down in vscode based on templates in the __templates folder.
Which would mean instead of
F1->Create Haxe Project or
F1->Create Flixel Project or
F1->Create Openfl Project
it would be
F1->Create Haxe Project
which provides new list
Template name 1, template name 2, Haxe Default, Flixel Default, Openfl Default, HaxeUI template...

**Comment by Jarrio** [comment]
I was actually going to start working on an option to group the create projects into a drop down next. 

As for the alternative templates directory, I can add a config setting which would ask the user if they wanted to use a custom template directory, request the location, copy the templates to that directory and use that as the default? I don't think it would be an elegant solution to just copy them straight to the Haxe installation folder

**Comment by hoseyjoe** [comment]
ya, good point.  the end goal is giving developers an easier way to add templates that arent maintained by the system

**Comment by Jarrio** [comment]
If you have any suggestions/templates let me know. Right now I'm mostly using haxe react native, flixel and basic Haxe projects. The react native projects are a little awkward to template so i'm saving that for another day. But I'm more than happy to add more platforms.

**Comment by hoseyjoe** [comment]
I'm an openfl, nme, haxeui-> html5, exe, app output sorta workflow currently.  I think the main thing there is choosing multiple debugs (windows/osx/android/html5...) If I make any good templates Ill pass them on

**Comment by Jarrio** [comment]
I've published an update to the extension. To use a custom template folder set the property `hxmanager.templatePath` to any path you wish, although right now it's not really a "plug and play" deal (as in new projects types won't be shown in the list but current templates can be adjusted and will be used instead). I will be adding that at a later date though as it just seems logical.

A change like that though would require some thought into adding "property files" with each project type which I haven't decided on yet
